openapi: 3.0.0
externalDocs:
  url: https://data.gov.hk/en-data/dataset/hk-edb-schinfo-school-location-and-information
info:
  title: Nearest Schools API
  description: Returns a list of the nearest schools to a given location.
  version: 1.0.0
  contact:
    name: Neo Alienson
    email: 'neo@01man.com'
    url: https://openapihk.github.io/portal
  termsOfService: https://openapihk.github.io/misc/terms_of_service.html
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html  
servers:
  - url: https://api.data.gov.hk/v1
paths:
  /nearest-schools:
    get:
      summary: Returns a list of the nearest schools to a given location.
      description: >
        This endpoint returns a list of the nearest schools to a given location,
        based on the specified search parameters.
      parameters:
        - in: query
          name: lat
          description: Latitude of enquiry location (WGS84)
          required: true
          schema:
            type: number
            format: float
        - in: query
          name: long
          description: Longitude of enquiry location (WGS84)
          required: true
          schema:
            type: number
            format: float
        - in: query
          name: max
          description: Maximum number of results returned (default:all, limit:100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  schools:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the school.
                        address:
                          type: string
                          description: The address of the school.
                        distance:
                          type: number
                          format: float
                          description: The distance between the search location and the school in meters.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: An error message indicating the reason for the bad request.
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: An error message indicating the reason for the internal server error.
